---
title: "AD Stanfile"
author: "Alex Dombowsky"
date: "3/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(tibble)
library(rstanarm)
library(latex2exp)
library(tidyr)
library(rstan)
```

```{r}
### Set up ###

# Generate hospital index 
hosp <- read.csv("hosp_full.csv", header=TRUE)
hosp_table <- data.frame(id = unique(hosp$id), hosp_index = c(1:length(unique(hosp$id))))
hosp <- inner_join(hosp, hosp_table) %>%
  filter(category!="Overall")
hosp_red <- read.csv("hosp.csv") # "reduced" hospital data


y = hosp$deaths
n = hosp$procedures
X = model.matrix(deaths ~ category, data=hosp)[, -1]
Z =  model.matrix(deaths ~ -1 + log(procedures) + top50_ped_cardio, data=hosp_red)

g = hosp$hosp_index

N = nrow(hosp)
M = length(unique(hosp$id))
K = ncol(X)
P = ncol(Z)


### Actually Sampling ###
stan_data = list(N=N, M = M, K = K, P = P, n=n, y = y, x = X, z = Z, g = g)

options(mc.cores = 2)
start_time <- Sys.time()
fit1 <- stan("JK_ADSM.stan", data = stan_data, chains = 2, iter = 5000, cores = 2)
end_time <- Sys.time()

end_time - start_time


### Summaries ###
alpha <- summary(fit1, pars = "a", probs = c(0.025, 0.975))$summary
alpha <- as.data.frame(alpha)
alpha[, c(1,3,4,5)]

mu <- summary(fit1, pars = "mu", probs = c(0.025, 0.975))$summary
mu <- as.data.frame(mu)
mu[, c(1,3,4,5)]

stan_hist(fit1, pars = c("alpha", "xi")) # all hospital random effect coefficients shrunk near zero besides intercept... probably due to sparsity

stan_plot(fit1, pars = "a") # all a's are more or less shrunk towards the intercept

``` 

